package mybeans;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class DataSheetTable extends JPanel {
    private JPanel panel1;
    private JPanel panelButtons;
    private JButton addButton;
    private JButton delButton;
    private JTable table;
    private DataSheetTableModel tableModel;

    public DataSheetTable() {
        $$$setupUI$$$();
        addButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                tableModel.setRowCount(tableModel.getRowCount() + 1);
                tableModel.getDataSheet().addDataItem(new Data());
                table.revalidate();
                tableModel.fireDataSheetChange();
            }
        });

        delButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (tableModel.getRowCount() > 1) {
                    tableModel.setRowCount(tableModel.getRowCount() - 1);
                    tableModel.getDataSheet().removeDataItem(tableModel.getDataSheet().size() - 1);
                    table.revalidate();
                    tableModel.fireDataSheetChange();
                } else {
                    tableModel.getDataSheet().getDataItem(0).setDate("");
                    tableModel.getDataSheet().getDataItem(0).setX(0);
                    tableModel.getDataSheet().getDataItem(0).setY(0);
                    table.revalidate();
                    table.repaint();
                    tableModel.fireDataSheetChange();
                }
            }
        });
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here
        table = new JTable();
        tableModel = new DataSheetTableModel();
        table.setModel(tableModel);
        table.getTableHeader().setBackground(new Color(-14067554));
        table.getTableHeader().setForeground(new Color(-1));
    }

    public DataSheetTableModel getTableModel() {
        return tableModel;
    }

    public void setTableModel(DataSheetTableModel tableModel) {
        this.tableModel = tableModel;
        table.revalidate();
    }

    public void revalidate() {
        if (table != null) table.revalidate();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        panel1.setBackground(new Color(-1));
        panel1.setForeground(new Color(-16777216));
        panel1.setMinimumSize(new Dimension(300, 200));
        panel1.setPreferredSize(new Dimension(300, 200));
        panelButtons = new JPanel();
        panelButtons.setLayout(new FlowLayout(FlowLayout.CENTER, 25, 5));
        panelButtons.setBackground(new Color(-1));
        panelButtons.setForeground(new Color(-16777216));
        panel1.add(panelButtons, BorderLayout.SOUTH);
        addButton = new JButton();
        addButton.setBackground(new Color(-12792538));
        addButton.setForeground(new Color(-1));
        addButton.setText("Add(+)");
        panelButtons.add(addButton);
        delButton = new JButton();
        delButton.setBackground(new Color(-4509650));
        delButton.setForeground(new Color(-1));
        delButton.setText("Del(-)");
        panelButtons.add(delButton);
        final JScrollPane scrollPane1 = new JScrollPane();
        scrollPane1.setBackground(new Color(-1));
        scrollPane1.setForeground(new Color(-16777216));
        panel1.add(scrollPane1, BorderLayout.CENTER);
        table.setBackground(new Color(-1));
        table.setForeground(new Color(-16777216));
        table.setGridColor(new Color(-12828863));
        table.setSelectionForeground(new Color(-1));
        scrollPane1.setViewportView(table);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

}
