package myApplication;

import mybeans.*;
import xml.DataSheetToXML;
import xml.SAXRead;

import javax.swing.*;
import java.awt.*;
import java.io.File;

public class JavaBeansGUI extends JFrame {
    private JButton openButton;
    private JButton saveButton;
    private JButton clearButton;
    private JButton endButton;
    private DataSheetTable dataSheetTable = null;
    private DataSheetGraph dataSheetGraph = null;
    private JPanel panel;
    private DataSheet dataSheet;
    private final JFileChooser fileChooser = new JFileChooser();

    public JavaBeansGUI() throws HeadlessException {
        $$$setupUI$$$();
        fileChooser.setCurrentDirectory(new File("."));
        openButton.addActionListener(e -> {
            if (JFileChooser.APPROVE_OPTION == fileChooser.showOpenDialog(null)) {
                String fileName = fileChooser.getSelectedFile().getPath();
                dataSheet = SAXRead.XMLReadData(fileName);
                dataSheetTable.getTableModel().setDataSheet(dataSheet);
                dataSheetTable.revalidate();
                dataSheetGraph.setDataSheet(dataSheet);
            }
        });
        saveButton.addActionListener(e -> {
            if (JFileChooser.APPROVE_OPTION == fileChooser.showSaveDialog(null)) {
                String fileName = fileChooser.getSelectedFile().getPath();
                DataSheetToXML.saveXMLDoc(DataSheetToXML.createDataSheetDOM(dataSheet), fileName);
                JOptionPane.showMessageDialog(null, "File " + fileName.trim() + " saved!", "Результати збережені", JOptionPane.INFORMATION_MESSAGE);
            }
        });
        clearButton.addActionListener(e -> {
            dataSheet = new DataSheet();
            dataSheet.addDataItem(new Data());
            dataSheetTable.getTableModel().setDataSheet(dataSheet);
            dataSheetTable.revalidate();
            dataSheetGraph.setDataSheet(dataSheet);
        });
        endButton.addActionListener(e -> dispose());
        setContentPane(panel);
        setTitle("Приклад JavaBeans");
        setPreferredSize(new Dimension(612, 400));
        setResizable(false);
        setVisible(true);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        pack();
    }

    public static void main(String[] args) {
        JFrame test = new JavaBeansGUI();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        panel.setLayout(new BorderLayout(0, 0));
        panel.setBackground(new Color(-1));
        panel.setMinimumSize(new Dimension(600, 400));
        panel.setPreferredSize(new Dimension(600, 400));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        panel1.setBackground(new Color(-1));
        panel1.setMinimumSize(new Dimension(600, 40));
        panel1.setPreferredSize(new Dimension(600, 40));
        panel.add(panel1, BorderLayout.SOUTH);
        openButton = new JButton();
        openButton.setBackground(new Color(-12792538));
        openButton.setForeground(new Color(-1));
        openButton.setText("Відкрити");
        panel1.add(openButton);
        saveButton = new JButton();
        saveButton.setBackground(new Color(-1258202));
        saveButton.setEnabled(true);
        saveButton.setForeground(new Color(-1));
        saveButton.setText("Зберегти");
        panel1.add(saveButton);
        clearButton = new JButton();
        clearButton.setBackground(new Color(-14067554));
        clearButton.setForeground(new Color(-1));
        clearButton.setText("Очистити");
        panel1.add(clearButton);
        endButton = new JButton();
        endButton.setBackground(new Color(-4509650));
        endButton.setForeground(new Color(-1));
        endButton.setText("Завершити");
        panel1.add(endButton);
        panel.add(dataSheetTable.$$$getRootComponent$$$(), BorderLayout.WEST);
        dataSheetGraph = new DataSheetGraph();
        panel.add(dataSheetGraph, BorderLayout.EAST);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel;
    }

    private void createUIComponents() {
        panel = new JPanel();
        panel.setLayout(new BorderLayout());
        panel.setMinimumSize(new Dimension(600, 400));
        panel.setPreferredSize(new Dimension(600, 400));

        dataSheet = new DataSheet();
        dataSheet.addDataItem(new Data());

        dataSheetTable = new DataSheetTable();
        dataSheetTable.getTableModel().setDataSheet(dataSheet);
        dataSheetTable.getTableModel().addDataSheetChangeListener(e -> {
            dataSheetGraph.revalidate();
            dataSheetGraph.repaint();
        });
        panel.add(dataSheetTable, BorderLayout.WEST);
    }
}
