package client;

import registry.Participant;
import registry.Registerable;


import javax.swing.*;
import java.awt.*;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;

public class Client extends JFrame {
    public static JTextField hostField;
    private JTextField portField;
    public static JTextField partField;
    private JButton finishButton;
    private JButton getInfoButton;
    private JButton clearButton;
    private JButton registerButton;
    private JTextField nameField;
    private JTextField surnameField;
    private JTextField orgField;
    private JTextField reportField;
    private JTextField emailField;
    private JPanel panel2;
    private JLabel hostLabel;
    private JLabel portLabel;
    private JLabel participantsLabel;
    private JPanel panel;
    private Registry registry = null;
    Registerable stub = null;

    public Client() {
        $$$setupUI$$$();
        registerButton.addActionListener(e -> {
            partField.setText("0");
            int port = Integer.parseInt(portField.getText());
            String host = hostField.getText();
            try {
                registry = LocateRegistry.getRegistry(host, port);
                String rname = "Registerable";
                stub = (Registerable) registry.lookup(rname);
                String name = nameField.getText();
                String surname = surnameField.getText();
                String organization = orgField.getText();
                String report = reportField.getText();
                String email = emailField.getText();
                Participant user = new Participant(name, surname, organization, report, email);
                stub.registry(user);
            } catch (RemoteException | NotBoundException remoteException) {
                remoteException.printStackTrace();
            }
        });
        clearButton.addActionListener(e -> {
            nameField.setText("");
            surnameField.setText("");
            orgField.setText("");
            reportField.setText("");
            emailField.setText("");
        });
        getInfoButton.addActionListener(e -> {
            try {
                stub.getInfo();
            } catch (RemoteException remoteException) {
                remoteException.printStackTrace();
            }
        });
        finishButton.addActionListener(e -> System.exit(0));
        setContentPane(panel);
        setTitle("Conference Client");
        setPreferredSize(new Dimension(612, 400));
        setResizable(false);
        setVisible(true);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        pack();
    }

    public static void main(String[] args) {
        new Client();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        panel.setLayout(new BorderLayout(0, 0));
        panel.add(panel2, BorderLayout.NORTH);
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        panel.add(panel1, BorderLayout.SOUTH);
        registerButton = new JButton();
        registerButton.setText("Register");
        panel1.add(registerButton);
        clearButton = new JButton();
        clearButton.setText("Clear");
        panel1.add(clearButton);
        getInfoButton = new JButton();
        getInfoButton.setText("Get Info");
        panel1.add(getInfoButton);
        finishButton = new JButton();
        finishButton.setText("Finish");
        panel1.add(finishButton);
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new GridBagLayout());
        panel.add(panel3, BorderLayout.CENTER);
        final JLabel label1 = new JLabel();
        label1.setText("Name: ");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        panel3.add(label1, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel3.add(spacer1, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.VERTICAL;
        panel3.add(spacer2, gbc);
        final JLabel label2 = new JLabel();
        label2.setText("Surname: ");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        panel3.add(label2, gbc);
        final JLabel label3 = new JLabel();
        label3.setText("Organization: ");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        panel3.add(label3, gbc);
        final JLabel label4 = new JLabel();
        label4.setText("Report: ");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 6;
        gbc.anchor = GridBagConstraints.WEST;
        panel3.add(label4, gbc);
        final JLabel label5 = new JLabel();
        label5.setText("Email: ");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 8;
        gbc.anchor = GridBagConstraints.WEST;
        panel3.add(label5, gbc);
        final JPanel spacer3 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.fill = GridBagConstraints.VERTICAL;
        panel3.add(spacer3, gbc);
        final JPanel spacer4 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 5;
        gbc.fill = GridBagConstraints.VERTICAL;
        panel3.add(spacer4, gbc);
        final JPanel spacer5 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 7;
        gbc.fill = GridBagConstraints.VERTICAL;
        panel3.add(spacer5, gbc);
        surnameField = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel3.add(surnameField, gbc);
        orgField = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel3.add(orgField, gbc);
        reportField = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 6;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel3.add(reportField, gbc);
        emailField = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 8;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel3.add(emailField, gbc);
        nameField = new JTextField();
        nameField.setColumns(25);
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel3.add(nameField, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() { return panel; }

    private void createUIComponents() {
        panel = new JPanel();
        panel2 = new JPanel();
        panel2.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        hostLabel = new JLabel();
        hostLabel.setText("host: ");
        panel2.add(hostLabel);
        hostField = new JTextField();
        hostField.setColumns(10);
        panel2.add(hostField);
        portLabel = new JLabel();
        portLabel.setText("port:");
        panel2.add(portLabel);
        portField = new JTextField();
        portField.setColumns(5);
        panel2.add(portField);
        participantsLabel = new JLabel();
        participantsLabel.setText("participants:");
        panel2.add(participantsLabel);
        partField = new JTextField();
        partField.setEnabled(false);
        partField.setColumns(5);
        panel2.add(partField);
        panel.add(panel2);
    }
}

